services:
  ubuntu2204:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu2204.Dockerfile
    environment:
      - LIBVA_DRIVER_NAME=d3d12
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - ./output:/output
  ubuntu2404:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu2404.Dockerfile
    environment:
      - LIBVA_DRIVER_NAME=d3d12
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - ./output:/output