services:
  ubuntu-22.04:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu/22.04/Dockerfile
    environment:
      - LIBVA_DRIVER_NAME=d3d12
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - ./shared:/shared
  ubuntu-24.04:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu/24.04/Dockerfile
    environment:
      - LIBVA_DRIVER_NAME=d3d12
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - ./shared:/shared
  ubuntu-24.04-plex:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu/24.04/plex.Dockerfile
    environment:
      - LIBVA_DRIVER_NAME=d3d12
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - PUID=0
      - PGID=0
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - ./shared:/shared
      - ./shared/plex:/config